import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:sampatti_bazar/core/theme/app_theme.dart';
import 'package:sampatti_bazar/features/auth/data/user_repository.dart';
import 'package:sampatti_bazar/features/chat/data/chat_repository.dart';
import 'package:sampatti_bazar/features/chat/domain/message_model.dart';
import 'package:timeago/timeago.dart' as timeago;
import 'package:url_launcher/url_launcher.dart';
import 'package:sampatti_bazar/features/properties/data/property_repository.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:go_router/go_router.dart';

class ChatDetailScreen extends ConsumerStatefulWidget {
  final String chatId;
  const ChatDetailScreen({super.key, required this.chatId});

  @override
  ConsumerState<ChatDetailScreen> createState() => _ChatDetailScreenState();
}

class _ChatDetailScreenState extends ConsumerState<ChatDetailScreen> {
  final _messageController = TextEditingController();
  final _scrollController = ScrollController();

  @override
  void dispose() {
    _messageController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  void _sendMessage() async {
    final text = _messageController.text.trim();
    if (text.isEmpty) return;

    final user = ref.read(currentUserDataProvider).value;
    if (user == null) return;

    final message = MessageModel(
      id: '', // Will be generated by Firestore
      senderId: user.uid,
      text: text,
      timestamp: DateTime.now(),
    );

    _messageController.clear();
    await ref.read(chatRepositoryProvider).sendMessage(widget.chatId, message);
    
    // Scroll to bottom after sending
    _scrollController.animateTo(
      0.0,
      duration: const Duration(milliseconds: 300),
      curve: Curves.easeOut,
    );
  }

  @override
  Widget build(BuildContext context) {
    final userAsync = ref.watch(currentUserDataProvider);
    final messagesAsync = ref.watch(chatMessagesProvider(widget.chatId));
    final chatAsync = ref.watch(userChatsProvider(userAsync.value?.uid ?? ''));

    return Scaffold(
      backgroundColor: context.scaffoldColor,
      appBar: AppBar(
        titleSpacing: 0,
        title: chatAsync.when(
          data: (chats) {
            final chat = chats.firstWhere((c) => c.id == widget.chatId, orElse: () => chats.first);
            final otherId = chat.getOtherMemberId(userAsync.value?.uid ?? '');
            final otherUserAsync = ref.watch(userProfileProvider(otherId));
            
            return otherUserAsync.when(
              data: (otherUser) => Row(
                children: [
                  CircleAvatar(
                    radius: 18,
                    backgroundColor: AppTheme.primaryBlue.withValues(alpha: 0.1),
                    child: Text(otherUser?.name?.substring(0, 1).toUpperCase() ?? '?', 
                               style: const TextStyle(color: AppTheme.primaryBlue, fontSize: 14, fontWeight: FontWeight.bold)),
                  ),
                  const SizedBox(width: 12),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(otherUser?.name ?? 'User', style: TextStyle(color: context.primaryTextColor, fontWeight: FontWeight.w900, fontSize: 15)),
                      Text('Online', style: TextStyle(color: Colors.green, fontSize: 10, fontWeight: FontWeight.bold)),
                    ],
                  ),
                ],
              ),
              loading: () => const Text('Chat', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w900)),
              error: (_, __) => const Text('Chat', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w900)),
            );
          },
          loading: () => const Text('Chat', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w900)),
          error: (_, __) => const Text('Chat', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w900)),
        ),
        backgroundColor: context.scaffoldColor,
        elevation: 0,
        actions: [
          IconButton(icon: Icon(Icons.videocam_outlined, color: context.primaryTextColor), onPressed: () {}),
          chatAsync.when(
            data: (chats) {
              final chat = chats.firstWhere((c) => c.id == widget.chatId, orElse: () => chats.first);
              final otherId = chat.getOtherMemberId(userAsync.value?.uid ?? '');
              return IconButton(
                icon: Icon(Icons.call_outlined, color: context.primaryTextColor), 
                onPressed: () async {
                  final otherUser = ref.read(userProfileProvider(otherId)).value;
                  if (otherUser?.phoneNumber != null) {
                    final uri = Uri.parse('tel:${otherUser!.phoneNumber}');
                    if (await canLaunchUrl(uri)) {
                      await launchUrl(uri);
                    }
                  } else {
                    ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Phone number not available')));
                  }
                },
              );
            },
            loading: () => const SizedBox.shrink(),
            error: (_, __) => const SizedBox.shrink(),
          ),
          const SizedBox(width: 8),
        ],
      ),
      body: userAsync.when(
        data: (user) {
          if (user == null) return const Center(child: Text('Please log in'));

          return Column(
            children: [
              chatAsync.when(
                data: (chats) {
                  final chat = chats.firstWhere((c) => c.id == widget.chatId, orElse: () => chats.first);
                  return _ContextCard(metadata: chat.metadata);
                },
                loading: () => const SizedBox.shrink(),
                error: (_, __) => const SizedBox.shrink(),
              ),
              Expanded(
                child: messagesAsync.when(
                  data: (messages) {
                    if (messages.isEmpty) {
                      return Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Icon(Icons.chat_bubble_outline, size: 48, color: context.secondaryTextColor.withValues(alpha: 0.2)),
                            const SizedBox(height: 16),
                            Text('Say hello!', style: TextStyle(color: context.secondaryTextColor, fontWeight: FontWeight.w500)),
                          ],
                        ),
                      );
                    }
                    return ListView.builder(
                      controller: _scrollController,
                      reverse: true,
                      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 20),
                      itemCount: messages.length,
                      itemBuilder: (context, index) {
                        final message = messages[index];
                        final isMe = message.senderId == user.uid;
                        return _MessageBubble(message: message, isMe: isMe);
                      },
                    );
                  },
                  loading: () => const Center(child: CircularProgressIndicator(color: AppTheme.primaryBlue)),
                  error: (e, st) => Center(child: Text('Error: $e')),
                ),
              ),
              SafeArea(child: _buildInputArea(context)),
            ],
          );
        },
        loading: () => const Center(child: CircularProgressIndicator(color: AppTheme.primaryBlue)),
        error: (e, st) => Center(child: Text('Error: $e')),
      ),
    );
  }

  Widget _buildInputArea(BuildContext context) {
    return Container(
      padding: const EdgeInsets.only(
        left: 16,
        right: 16,
        bottom: 24, // Let Scaffold handle keyboard, this is base padding
        top: 12,
      ),
      decoration: BoxDecoration(
        color: context.scaffoldColor,
        border: Border(top: BorderSide(color: context.borderColor, width: 0.5)),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: AppTheme.primaryBlue.withValues(alpha: 0.08),
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.add, color: AppTheme.primaryBlue, size: 20),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              decoration: BoxDecoration(
                color: context.isDarkMode ? Colors.grey[900] : Colors.grey[100],
                borderRadius: BorderRadius.circular(24),
              ),
              child: TextField(
                controller: _messageController,
                maxLines: null,
                style: TextStyle(color: context.primaryTextColor, fontSize: 15),
                decoration: InputDecoration(
                  hintText: 'Type a message...',
                  hintStyle: TextStyle(color: context.secondaryTextColor.withValues(alpha: 0.5)),
                  border: InputBorder.none,
                  contentPadding: const EdgeInsets.symmetric(vertical: 10),
                ),
              ),
            ),
          ),
          const SizedBox(width: 12),
          GestureDetector(
            onTap: _sendMessage,
            child: Container(
              padding: const EdgeInsets.all(12),
              decoration: const BoxDecoration(
                color: AppTheme.primaryBlue,
                shape: BoxShape.circle,
              ),
              child: const Icon(Icons.send_rounded, color: Colors.white, size: 18),
            ),
          ),
        ],
      ),
    );
  }
}

class _MessageBubble extends StatelessWidget {
  final MessageModel message;
  final bool isMe;

  const _MessageBubble({required this.message, required this.isMe});

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: isMe ? Alignment.centerRight : Alignment.centerLeft,
      child: Container(
        margin: const EdgeInsets.only(bottom: 12),
        constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width * 0.75),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        decoration: BoxDecoration(
          color: isMe ? AppTheme.primaryBlue : (context.isDarkMode ? Colors.grey[900] : Colors.grey[100]),
          borderRadius: BorderRadius.only(
            topLeft: const Radius.circular(20),
            topRight: const Radius.circular(20),
            bottomLeft: Radius.circular(isMe ? 20 : 4),
            bottomRight: Radius.circular(isMe ? 4 : 20),
          ),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              message.text,
              style: TextStyle(
                color: isMe ? Colors.white : context.primaryTextColor,
                fontSize: 14,
                fontWeight: FontWeight.w500,
              ),
            ),
            const SizedBox(height: 4),
            Text(
              timeago.format(message.timestamp),
              style: TextStyle(
                color: isMe ? Colors.white.withValues(alpha: 0.7) : context.secondaryTextColor,
                fontSize: 8,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _ContextCard extends ConsumerWidget {
  final Map<String, dynamic> metadata;
  const _ContextCard({required this.metadata});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    if (metadata.isEmpty) return const SizedBox.shrink();

    final propertyId = metadata['propertyId'];
    final type = metadata['type'];
    final category = metadata['category'];

    if (propertyId != null) {
      final propertyAsync = ref.watch(propertyProvider(propertyId));
      return propertyAsync.when(
        data: (property) {
          if (property == null) return const SizedBox.shrink();
          return Container(
            margin: const EdgeInsets.all(12),
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: context.cardColor,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: context.borderColor),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withValues(alpha: 0.03),
                  blurRadius: 10,
                  offset: const Offset(0, 4),
                )
              ],
            ),
            child: Row(
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(12),
                  child: property.imageUrls.isNotEmpty && property.imageUrls.first.isNotEmpty
                    ? CachedNetworkImage(
                        imageUrl: property.imageUrls.first,
                        width: 60,
                        height: 60,
                        fit: BoxFit.cover,
                        placeholder: (context, url) => Container(color: Colors.grey[200]),
                        errorWidget: (context, url, error) => Container(
                          color: Colors.grey[200],
                          child: const Icon(Icons.image_not_supported, color: Colors.grey, size: 20),
                        ),
                      )
                    : Container(
                        width: 60,
                        height: 60,
                        color: Colors.grey[200],
                        child: const Icon(Icons.image, color: Colors.grey, size: 20),
                      ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        property.title,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: context.primaryTextColor),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        '₹${property.price.toInt()}',
                        style: const TextStyle(color: AppTheme.primaryBlue, fontWeight: FontWeight.w900, fontSize: 13),
                      ),
                    ],
                  ),
                ),
                TextButton(
                  onPressed: () {
                    context.push('/properties/${property.id}');
                  },
                  child: const Text('View', style: TextStyle(fontSize: 12)),
                ),
              ],
            ),
          );
        },
        loading: () => const SizedBox.shrink(),
        error: (_, __) => const SizedBox.shrink(),
      );
    }

    if (type == 'service') {
      return Container(
        width: double.infinity,
        margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
        decoration: BoxDecoration(
          color: AppTheme.primaryBlue.withValues(alpha: 0.05),
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: AppTheme.primaryBlue.withValues(alpha: 0.1)),
        ),
        child: Row(
          children: [
            const Icon(Icons.info_outline, color: AppTheme.primaryBlue, size: 18),
            const SizedBox(width: 12),
            Expanded(
              child: Text(
                'Inquiry regarding: $category',
                style: const TextStyle(color: AppTheme.primaryBlue, fontSize: 13, fontWeight: FontWeight.w600),
              ),
            ),
          ],
        ),
      );
    }

    return const SizedBox.shrink();
  }
}
