// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCObaGD70yKKdTxGK3R3N_7agw7WsSm9T4',
    appId: '1:987957373561:web:5a1ee276460946803bc2a8',
    messagingSenderId: '987957373561',
    projectId: 'sampatti-bazar',
    authDomain: 'sampatti-bazar.firebaseapp.com',
    storageBucket: 'sampatti-bazar.firebasestorage.app',
    measurementId: 'G-J0HFXEZ1P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxBbtJh5KO4cLgMTy652YU8cL-rRPbXB8',
    appId: '1:987957373561:android:ccdfca1d15ef943a3bc2a8',
    messagingSenderId: '987957373561',
    projectId: 'sampatti-bazar',
    storageBucket: 'sampatti-bazar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5th-8BpiNYvXj3wAfPxuB5eiNZ6ln2Fs',
    appId: '1:987957373561:ios:cea57e69e3ca5a4c3bc2a8',
    messagingSenderId: '987957373561',
    projectId: 'sampatti-bazar',
    storageBucket: 'sampatti-bazar.firebasestorage.app',
    iosBundleId: 'com.sampattibazar.sampattiBazar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5th-8BpiNYvXj3wAfPxuB5eiNZ6ln2Fs',
    appId: '1:987957373561:ios:cea57e69e3ca5a4c3bc2a8',
    messagingSenderId: '987957373561',
    projectId: 'sampatti-bazar',
    storageBucket: 'sampatti-bazar.firebasestorage.app',
    iosBundleId: 'com.sampattibazar.sampattiBazar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCObaGD70yKKdTxGK3R3N_7agw7WsSm9T4',
    appId: '1:987957373561:web:3b2484696f2a30b73bc2a8',
    messagingSenderId: '987957373561',
    projectId: 'sampatti-bazar',
    authDomain: 'sampatti-bazar.firebaseapp.com',
    storageBucket: 'sampatti-bazar.firebasestorage.app',
    measurementId: 'G-83JC4VJVZ7',
  );
}
